# Generated by Django 4.2.24 on 2025-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_conductor',
            field=models.BooleanField(default=False, verbose_name='¿Es Conductor?'),
        ),
    ]
